### ISSUE TITLE
Please add a requirements.txt file

### ISSUE THREAD

**Issue by ghost** [jaeyeun97/MelNet#2]
Running the `main.py` gives a bunch of missing dependency errors.

System: `python 3.7` `pipenv`

I installed the following dependencies:
`apex adabound soundfile`

This gives the following error:
`Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from model import get_model_fn
  File "P:\Machine_Learning_Projects\Cloned\MelNet\model.py", line 7, in <module>
    from apex import amp
  File "P:\Machine_Learning_Projects\Cloned\MelNet\.venv\lib\site-packages\apex\__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "P:\Machine_Learning_Projects\Cloned\MelNet\.venv\lib\site-packages\apex\interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "P:\Machine_Learning_Projects\Cloned\MelNet\.venv\lib\site-packages\apex\interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "P:\Machine_Learning_Projects\Cloned\MelNet\.venv\lib\site-packages\zope\interface\declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')`

Message: `TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.`

I thought my virtual environment is messed up, so I reinstalled it again, and then tried it in google colab. All the time the result is the same.

**Comment by ghost** [comment]
reference: https://github.com/NVIDIA/apex/issues/116#issuecomment-451828768

issue with the apex module is solved by the following steps:
`pip uninstall apex`
`git clone https://www.github.com/nvidia/apex`
`cd apex`
`python setup.py install`

Dependency list:
`pip install tensorboardX torch torchaudio adabound soundfile`
(install apex by the first steps)

**Comment by jaeyeun97** [comment]
Haha you didn't even need me!
